server:
  port: 9999
debug: true

security: 
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/uaa/introspect
      prefer-token-info: true
    client:
      client-id: app
      client-secret: appclientsecret